Ignore cudf's __dataframe__ deprecation. (#6229)
Currently CI is failing due to
https://github.com/rapidsai/cudf/pull/17736.

The `__dataframe__` protocol appears to be used internally by
scikit-learn:
https://github.com/scikit-learn/scikit-learn/blob/311bf6badd74bb69081eb90e2643f15706d3473c/sklearn/utils/validation.py#L389

Errors look like:
```
FAILED test_metrics.py::test_sklearn_search - FutureWarning: Using `__dataframe__` is deprecated
```

This PR ignores the `FutureWarning` to allow CI to pass.

---------

Co-authored-by: Dante Gama Dessavre <danteg@nvidia.com>