Set default values for conftest options. (#6067)
There is no default being set for `run_ucx` or `run_ucxx`. This results in an error on Python 3.12 (maybe other versions too):

```
AttributeError: 'Namespace' object has no attribute 'run_ucx'. Did you mean: 'run_unit'?
```

This PR adds a default value for those conftest options.

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Divye Gala (https://github.com/divyegala)

URL: https://github.com/rapidsai/cuml/pull/6067