Fix np.NAN to np.nan. (#6056)
NumPy 2 requires `np.nan` instead of `np.NAN`. This appeared as a nightly test failure:

```
FAILED test_kernel_ridge.py::test_estimator - AttributeError: module 'numpy' has no attribute 'NAN'
```

Referencing the NumPy 2 changelog: https://numpy.org/devdocs/release/2.0.0-notes.html

> Alias np.NaN has been removed. Use np.nan instead.

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Divye Gala (https://github.com/divyegala)

URL: https://github.com/rapidsai/cuml/pull/6056