Fix import in benchmark code in algorithms.py that was causing an error (#6902)
Moving the import to the local context was causing the following issue:

```python
(rapids) coder ➜ ~/cuml/cuml-accel-bench $ bash bench.sh 
Traceback (most recent call last):
  File "/home/coder/cuml/python/cuml/cuml/benchmark/run_benchmarks.py", line 262, in <module>
    algo = algorithms.algorithm_by_name(name)
  File "/home/coder/cuml/python/cuml/cuml/benchmark/algorithms.py", line 837, in algorithm_by_name
    algos = all_algorithms()
  File "/home/coder/cuml/python/cuml/cuml/benchmark/algorithms.py", line 227, in all_algorithms
    cuml.cluster.KMeans,
    ^^^^
UnboundLocalError: cannot access local variable 'cuml' where it is not associated with a value
```

where bench.sh was just a call to use the benchmark code:

```bash
export NROWS=1000000

python /opt/conda/lib/python3.12/site-packages/cuml/benchmark/run_benchmarks.py LinearRegression ElasticNet Lasso --num-rows $NROWS --dataset regression --input-type numpy --csv LinearRegressionCPU$NROWS.csv
```

this PR fixes that by using importlib.

Authors:
  - Dante Gama Dessavre (https://github.com/dantegd)

Approvers:
  - Simon Adorf (https://github.com/csadorf)

URL: https://github.com/rapidsai/cuml/pull/6902