`TargetEncoder` in cuml.accel (#7476)
Resolves https://github.com/rapidsai/cuml/issues/7154

This PR adds support for TargetEncoder in cuml.accel. This feature was originally requested by the kaggle team.

TargetEncoder is a preprocessing step to convert categorical features like `"cat", "dog"` into numerical values. It uses the mean of the categories target values to obtain a numerical value.

There are API differences between cuml and sklearn's implementation of TargetEncoder and these differences must be handled in translating between cpu and gpu models.

| **cuML TargetEncoder param** | **sklearn TargetEncoder param** | **Transformation / Notes** |
|-------------------------------|------------------------------------|-----------------------------|
| `n_folds`                    | `cv`                               | Direct mapping |
| `seed`                       | `random_state`                     | If `random_state` is `None`, defaults to `42` |
| `smooth`                     | `smooth`                           | If `smooth == "auto"`, set to `1.0`; else `float(model.smooth)` |
| `split_method`               | `shuffle`                          | `"random"` if `shuffle=True`, otherwise `"continuous"` |
| `output_type`                | *(no sklearn equivalent)*          | Always `"auto"` |
| `stat`                       | *(no sklearn equivalent)*          | Always `"mean"` |
| *(no cuml equivalent)*        | `categories`                       | Always `"auto"` |
| *(no cuml equivalent)*        | `target_type`                      | Always `"continuous"` |

## Testing upstream

```bash
./run-tests.sh -k "targetencoder"
```

Current failures
```bash
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_n_features_in_after_fitting] - AssertionError: `TargetEncoder.fit()` does not set the `n_features_in_` attribute. You might want to use `sklearn.utils.validation.validate_data` instead of `check_array` in `TargetEncoder.fit()` which takes care of setting the attribute.
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_complex_data] - NotImplementedError: complex128 not supported
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_dtype_object] - cudf.errors.MixedTypeError: Cannot convert a floating of object type
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_estimators_empty_data_messages] - AssertionError: The estimator TargetEncoder does not raise a ValueError when an empty data is used to train. Perhaps use check_array in train.
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_estimators_pickle] - AttributeError: DataFrame object has no attribute to_output
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_estimators_pickle(readonly_memmap=True)] - AttributeError: DataFrame object has no attribute to_output
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_transformer_data_not_an_array] - AttributeError: '_NotAnArray' object has no attribute 'shape'
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_transformer_general] - AssertionError: The transformer TargetEncoder does not raise an error when the number of features in transform is different from the number of features in fit.
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_transformer_general(readonly_memmap=True)] - AssertionError: The transformer TargetEncoder does not raise an error when the number of features in transform is different from the number of features in fit.
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_methods_sample_order_invariance] - AssertionError: 
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_methods_subset_invariance] - AssertionError: 
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_n_features_in] - AssertionError
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_fit1d] - AssertionError: Did not raise: [<class 'ValueError'>]
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_fit2d_predict1d] - KeyError: '__FEA__'
FAILED tests/test_common.py::test_estimators[TargetEncoder()-check_requires_y_none] - TypeError: Input of type <class 'NoneType'> is not cudf.Series, or pandas.Seriesor numpy.ndarrayor cupy.ndarray
FAILED tests/test_common.py::test_pandas_column_name_consistency[TargetEncoder()] - ValueError: Estimator does not have a feature_names_in_ attribute after fitting with a dataframe
FAILED tests/test_docstring_parameters.py::test_fit_docstring_attributes[TargetEncoder-TargetEncoder] - AssertionError: assert False
================================================================================================================================= 17 failed, 43 passed, 1 skipped, 44347 deselected, 32 warnings in 15.23s ==================================================================================================================================
```

## Testing local

```bash
pytest test_sklearn_import_export.py -k "target_encoder"
```

Current failures
```bash
AttributeError: 'TargetEncoder' object has no attribute 'categories_'. Did you mean: 'categories'?
============================== short test summary info ==============================
FAILED test_sklearn_import_export.py::test_target_encoder - AttributeError: 'TargetEncoder' object has no attribute 'categories_'. Did you m...
```

Authors:
  - Anupam (https://github.com/aamijar)
  - Dante Gama Dessavre (https://github.com/dantegd)
  - Simon Adorf (https://github.com/csadorf)

Approvers:
  - Simon Adorf (https://github.com/csadorf)
  - James Lamb (https://github.com/jameslamb)

URL: https://github.com/rapidsai/cuml/pull/7476