Use cudf.Index instead of cudf.GenericIndex. (#5738)
I saw the cuml docs build failed, with the error below:

```
Failed to import cuml.compose.
Possible hints:
* AttributeError: module 'cudf' has no attribute 'GenericIndex'
* KeyError: 'cuml'
```

This is due to pandas 2 changes in cudf that need updated in cuml. This PR is unlikely to contain the full changeset of things needed for pandas 2 support, but it fixes one problem and we can let CI tell us the rest of the failures.

Authors:
   - Bradley Dice (https://github.com/bdice)

Approvers:
   - Dante Gama Dessavre (https://github.com/dantegd)