Fix `scikit-learn` version specifier (#6158)
This version should be `1.5.*`, otherwise this causes pip solves to fail with the following error when included with a wheel downloaded via `pip download`:

```
ERROR: Cannot install scikit-learn, scikit-learn 1.5.2 (from scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) and scikit-learn==1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested scikit-learn 1.5.2 (from scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
    The user requested scikit-learn
    The user requested scikit-learn==1.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

Authors:
  - Paul Taylor (https://github.com/trxcllnt)

Approvers:
  - Bradley Dice (https://github.com/bdice)
  - Dante Gama Dessavre (https://github.com/dantegd)

URL: https://github.com/rapidsai/cuml/pull/6158